# Generated by Django 4.1.4 on 2023-01-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="slug",
            field=models.TextField(default="Product"),
        ),
    ]
